version: '3'

services:
  user:
    image: openjdk:17-jdk-alpine
    ports:
      - "9000:8080"
    volumes:
      - ./target:/app
    working_dir: /app
    command: ["java", "-jar", "user-0.0.1-SNAPSHOT.jar"]

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: db-ms-user
      MYSQL_USER: emendoza
      MYSQL_PASSWORD: emi123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql